### ISSUE TITLE
[IMPORTANT] Project unmaintained. Please migrate to 'rickstaa/tmux-notify'

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/tmux-notify#38]
> > oh I agree, I typically despise forks as people are too quick to fork rather than try to work with maintainers. but in the case where a maintainer has ghosted the repo and people are using it I think it's the only way. GitHub Support historically doesn't intervene when I wish they would.
>
> Same here, de-forking is my last resort 😅. However, the last response I received from the author was more than 3 years ago (see https://github.com/ChanderG/tmux-notify/issues/16#issuecomment-703053967) and I tried to contact him on all channels. 
>
> The de-forking just finished, and it looks like all the history was retained 🎉. The only contributor that is not shown any more is @bruno- because I think those initial commits were cherry-picks. Anyway, we are good to continue the maintained on my new orphan repository 👍🏻. Alternatively, as stated in https://github.com/ChanderG/tmux-notify/issues/16 I'm also okay with transferring the repository to the https://github.com/tmux-plugins organization and maintaining it from there if @bruno-, @ctjhoa and @jbnicolai are interested. I think there it would even reach more people.

_Originally posted by @rickstaa in https://github.com/ChanderG/tmux-notify/issues/28#issuecomment-1584456420_
            
As explained in the post above, @ChanderG no longer seems to maintain this repository :slightly_frowning_face:. Since I wanted more control while maintaining this project, I detached [my fork](https://github.com/rickstaa/tmux-notify) and will maintain this project there. I'm happy to detach it again in the future, might @ChanderG return to help me maintain it 👍🏻.

## How to migrate to the new upstream

To migrate to the new upstream (i.e. https://github.com/rickstaa/tmux-notify), change the following line:

```bash
set -g @plugin 'ChanderG/tmux-notify'
```

to:

```bash
set -g @plugin 'rickstaa/tmux-notify'
```

in your `.tmux.conf`.

**Comment by ChanderG** [comment]
@rickstaa Hi Rick. Just saw this. I am not in a position to maintain this and your move is absolutely the right one - since you have put in all the effort since the very beginning. I did see some notifications ever so often and intended to come back at some point - but that never materialized.

Is there something I can do to make your life easier? I can transfer this repo over to you or to an org like tmux-plugins - if you want the history of issues/PRs etc.

Again, my contributions were only in the initial structure and setup - it was Rick who put in the active effort to grow and maintain this, so thanks to @rickstaa for all of that.

**Comment by rickstaa** [comment]
> @rickstaa Hi Rick. Just saw this. I am not in a position to maintain this and your move is absolutely the right one - since you have put in all the effort since the very beginning. I did see some notifications ever so often and intended to come back at some point - but that never materialized.
> 
> Is there something I can do to make your life easier? I can transfer this repo over to you or to an org like tmux-plugins - if you want the history of issues/PRs etc.
> 
> Again, my contributions were only in the initial structure and setup - it was Rick who put in the active effort to grow and maintain this, so thanks to @rickstaa for all of that.

@ChanderG, thanks for taking the time to answer me. No problem at all! Life can leave little time for maintaining OS projects. I also had to hand over control for other projects I could no longer maintain 😅. I chose to maintain this project because you made something very cool, and I use the tool daily. 

I prefer transferring it to https://github.com/tmux-plugins because the plugin will have more reach there, and we both have control over the repository 🚀. If @bruno-, @ctjhoa and @jbnicolai don't yet want to merge this plugin into the organization because our userbase is relatively small, we can do the following:

- I will attach my detached fork to the upstream again.
- I will merge the commits of the last three weeks into the upstream.
- You transfer the repository to my account (see https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository). 

This way, I will have more control over the repository (i.e. settings, applications, secrets, actions etc.), making it easier to maintain. In contrast, you still have full permission to merge any PR.

**Comment by rickstaa** [comment]
@ChanderG I just asked GitHub to attach my fork again. I think after it is attached we can transfer the repository to my account, and I can give you the most permissive collaborator permissions. If the [tmux-plugins](https://github.com/tmux-plugins) maintainers answer, we can transfer it to the organization 👍🏻. I will let you know when the re-attachment is done.

**Comment by rickstaa** [comment]
@henriqueffc, @odonckers, @cynicaljoy for your info.

**Comment by rickstaa** [comment]
@ChanderG, you can transfer the repository to my username (see https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) 👍🏻.

**Comment by ChanderG** [comment]
@rickstaa Just tried to transfer over the repo - but it failed since a repo with the same name exists in your account. What is the best way to proceed without breaking anything? Did you check with the tmux-plugins folks?

**Comment by rickstaa** [comment]
> @rickstaa Just tried to transfer over the repo - but it failed since a repo with the same name exists in your account. What is the best way to proceed without breaking anything? Did you check with the tmux-plugins folks?

Strange, I would have thought GitHub should have handled the situation when there already is a fork since migrating to another fork is committed. I now renamed my fork to https://github.com/rickstaa/tmux-notify-fork so you can transfer the repository 👍🏻. Unfortunately, I did not hear back from the tmux-plugins maintainers.

**Comment by ChanderG** [comment]
Just tried to, but there is a new error this time:
![image](https://github.com/ChanderG/tmux-notify/assets/6350377/fc064dd4-a581-448e-8d7e-45a31093fe8b)

Looks like you can't transfer a repo if the destination owner has a fork in the same network, from the prerq here: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

![image](https://github.com/ChanderG/tmux-notify/assets/6350377/136eb2c8-3303-447d-ad86-2d8fe28697fd)

Not clear why this sort of rules exist... :-(

**Comment by rickstaa** [comment]
@ChanderG thank you so much for trying again. I have no idea why GitHub has those rules, as they don't make sense to me since most transfers are to other collaborators who will have a fork. Probably some safeguards to prevent server/routing problems 🤔. I removed my fork so that now it should work 👍🏻.

**Comment by rickstaa** [comment]
@ChanderG, thanks for transferring the repository 🚀. I will do my best to maintain it. I will transfer it to the next maintainer or the `tmux-plugins` organization if I can't find time. You are still a collaborator, so please create and merge any pull request you want 👍🏻.
